config/routes.rb
Rails.application.routes.draw do
  resources :recettes

  #Marquer recettes comme page principale
  root "recettes#index"
  get "/recettes", to: "recettes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recette.rb
class Recette < ApplicationRecord

  #Methode pour la barre de recherche
  def self.search(search)
    if search != '' && search
      Recette.where('lower(nom) LIKE ?', search.downcase)
    else
      Recette.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recettes_controller.rb
class RecettesController < ApplicationController
  def index
    @recettes = Recette.search(params[:search])
  end

  def show
    @recette = Recette.find(params[:id])
  end

  def new
    @recette = Recette.new
  end

  def create
    recette = Recette.create(recette_params)

    redirect_to recettes_path
  end


  def edit
    @recette = Recette.find(params[:id])
  end

  def update
    @recette = Recette.find(params[:id])
    @recette.update(recette_params)

    redirect_to recette_path(@recette)
  end

  def destroy
    @recette = Recette.find(params[:id])
    @recette.destroy

    redirect_to recettes_path
  end

  private

  def recette_params
    params.require(:recette).permit(:nom, :ingredients, :methode, :search)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recettes_helper.rb
module RecettesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recettes/edit.html.erb
<h3>Modifier la recette</h3>
<%= form_with model: @recette do |form| %>
  <%= form.text_field :nom, placeholder: "nom" %>
  <%= form.text_field :ingredients, placeholder: "ingrédients" %>
  <%= form.text_field :methode, placeholder: "méthode" %>
  <%= form.submit %>
<% end %>

app/views/recettes/index.html.erb
<h1>Recettes</h1>
<%= link_to "Ajouter une nouvelle recette", new_recette_path %>
<p></p>

<h4>Recherche par nom de recette: </h4>
   <%= form_tag(recettes_path, method: 'get') do %>
     <%= text_field_tag(:search, params[:search]) %>
     <%= submit_tag ("Rechercher") %>
   <% end %>
<p></p>
<table>
  <% @recettes.each do |recette| %>
    <tr>
      <td><%= link_to recette.nom, recette_path(recette) %></td>
      <td><%= button_to 'Modifier', edit_recette_path(recette), method: 'get'%></td>
      <td><%= button_to 'Supprimer', recette_path(recette), method: 'delete', data: { confirm: 'Vous êtes sure ?' } %></td>
  <% end %>
</table>

app/views/recettes/new.html.erb
<h3>Ajouter une recette</h3>
<%= form_with model: @recette do |form| %>
  <%= form.text_field :nom, placeholder: "nom" %>
  <%= form.text_field :ingredients, placeholder: "ingrédients" %>
  <%= form.text_field :methode, placeholder: "méthode" %>
  <%= form.submit %>
<% end %>

app/views/recettes/show.html.erb
<h1>Information Recette</h1>
<h2><%= @recette.nom %></h2>
<p><b>Ingrédients:</b> <%= @recette.ingredients %></p>
<p><b>Méthode:</b> <%= @recette.methode %></p>
<%= button_to 'Supprimer', recette_path(@recette), method: 'delete', data: { confirm: 'Vous êtes sure ?' } %>
<%= button_to 'Modifier', edit_recette_path(@recette), method: 'get'%>
<p><%= button_to 'Retour aux autres recettes', recettes_path, method: 'get'%></p>